/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-variant': '#e1e3e4',
        background: '#f8f9fa',
        'on-background': '#191c1d',
        'on-surface': '#191c1d',
        'on-surface-variant': '#44474d',
        outline: '#75777e',
        'outline-variant': '#c5c6cd',
        'surface-tint': '#515f78',
        primary: '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#0d1c32',
        'on-primary-container': '#76849f',
        secondary: '#0059bb',
        'on-secondary': '#ffffff',
        'secondary-container': '#0070ea',
        'on-secondary-container': '#fefcff',
        tertiary: '#000000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#271900',
        'on-tertiary-container': '#ac7b00',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#b9c7e4',
        'on-primary-fixed': '#0d1c32',
        'on-primary-fixed-variant': '#39475f',
        'secondary-fixed': '#d8e2ff',
        'secondary-fixed-dim': '#adc7ff',
        'on-secondary-fixed': '#001a41',
        'on-secondary-fixed-variant': '#004493',
        'tertiary-fixed': '#ffdea8',
        'tertiary-fixed-dim': '#ffba20',
        'on-tertiary-fixed': '#271900',
        'on-tertiary-fixed-variant': '#5e4200',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        'inverse-primary': '#b9c7e4',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '48px',
        gutter: '24px',
        'container-max': '1440px',
      },
      fontFamily: {
        sans: [
          'system-ui',
          '-apple-system',
          'Segoe UI',
          'Roboto',
          'Helvetica',
          'Arial',
          'Apple Color Emoji',
          'Segoe UI Emoji',
        ],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      },
      boxShadow: {
        'soft-navy': '0 16px 24px -12px rgba(10, 25, 47, 0.06)',
        'soft-navy-sm': '0 16px 24px rgba(10, 25, 47, 0.04)',
      },
    },
  },
  plugins: [],
}
